### ISSUE TITLE
[Help Needed] Integration with koa based server.

### ISSUE THREAD

**Issue by aga5tya** [FormidableLabs/rapscallion#108]
I am trying to implement rapscallion with a koa based SSR backend, but unable to get the streams implementation right. Are there any examples that can point me in the right direction? Any pointers will highly help me out :)

**Comment by divmain** [comment]
Hey @aga5tya.  We don't have any ready-made Koa examples, but the response objects should all operate the same under the hood.  Need more information to determine if this is a bug or if there's something missing on your end.

**Comment by aga5tya** [comment]
@divmain, Apologize for not sharing complete details, il push a repro in sometime. Probably something to do with the way I'm implementing.

**Comment by aga5tya** [comment]
@divmain I have pushed in a repro at, "yarn install && yarn run develop" should get the application up.
https://github.com/aga5tya/react-universally/tree/feature/rapscallion-integration

Key changes i did are at this commit.
https://github.com/aga5tya/react-universally/commit/4183a5069fd713d6a69ae50dc4e88250aca55b94

Let me know if you need any clarifications :)

**Comment by ethersage** [comment]
@aga5tya Without knowing the specific error or symptoms you're seeing, from the commit you posted I believe I see two potential issues:

1) [`ServerHTML`](https://github.com/aga5tya/react-universally/blob/4183a5069fd713d6a69ae50dc4e88250aca55b94/server/middleware/reactApplication/ServerHTML.js#L94-L107) appears to be a react component that returns a rapscallion renderer (by invoking `template`). This will not work, as the React renderer expects a [React element](https://facebook.github.io/react/blog/2014/10/14/introducing-react-elements.html) to be returned from the render method (or a stateless functionial component in this case).
2) I don't think this would cause any issues, but you do not need to embed renderers inside your template literal if they have the same options as their parent renderer (the template literal in this case). You can just embed your components or functions that return components in the literal.

I'm closing this issue, as I believe 1) above should be a good start for your issue. Please feel free to reopen if you are still having issues and please post as much information, including the error, as possible.  Thanks.
