### ISSUE TITLE
Plan to migrate to react@16?

### ISSUE THREAD

**Issue by mastilver** [FormidableLabs/rapscallion#114]
Hi, as you might be aware react is changing there file structure in the next release. So most of `rapscallion`'s imports now fails with the new version of `react` and `react-dom`. Do you have any plan to support react@16?

In the meantime, shouldn't `rapscallion` have `react` and `react-dom` as `peerDependencies`?

https://github.com/facebook/react/issues/10294
> There is no react/lib/* and react-dom/lib/* anymore. Even in CommonJS environments, React and ReactDOM are precompiled to single files (“flat bundles”). If you previously relied on undocumented React internals, and they don’t work anymore, let us know about your specific case in this issue, and we’ll try to figure out a migration strategy for you.

**Comment by aickin** [comment]
It's also worth noting that React 16 has some features that overlap with Rapscallion:

- Streaming is supported, with the new methods `renderToNodeStream` and `renderToNodeStaticMarkup`.
- Server rendering is now a **lot** faster than it was in React 15.

There are, however, some Rapscallion features that are not in React 16:

- You can not embed a stream in a component, so streaming HTML templating with `renderToNodeStaticMarkup` doesn't work.
- There is no caching strategy.

**Comment by theskillwithin** [comment]
would be interested in knowing the answer to this as well

**Comment by eberhara** [comment]
+1

**Comment by zackljackson** [comment]
What about opening a PR with: https://github.com/zackljackson/react-component-caching mapped into the API of rapscallion? Or at least the renderer of it?

**Comment by ryan-roemer** [comment]
Closing in favor of #120 which is most recent discussion of React16 support. (This ticket details the _why we need it_ more, but I think we all agree we need it, so I'm honing us down to one ticket 😛 )
