### ISSUE TITLE
Warning: render(): Target node has markup rendered by React, but there are unrelated nodes as well. This is most commonly caused by white-space inserted around server-rendered markup.

### ISSUE THREAD

**Issue by arnayak4u** [FormidableLabs/rapscallion#118]
After switching to Rapscallion template  toStream() , I am getting following Error/Warning on the browser: 

**Warning: render(): Target node has markup rendered by React, but there are unrelated nodes as well. This is most commonly caused by white-space inserted around server-rendered markup.**

My React SSR code looks somewhat like below :

    app.get('*', function (request, response) {
                   const responseRenderer = template`
                    <!doctype html>.....

                        <div id="appRoot">
                        ${componentRenderer}
                        </div>
<script/>......`
                    response.set('Content-Type', 'text/html');
                    responseRenderer.toStream().pipe(response);
})

**Comment by danieljuhl** [comment]
Have you tried `<div id="appRoot">${componentRenderer}</div>`

**Comment by spa-simone** [comment]
The solution suggested by @danieljuhl definitely works. I think this issue can be closed.

**Comment by ryan-roemer** [comment]
Thanks @danieljuhl and @spa-simone !
