### ISSUE TITLE
renderToString prints out class-name="" instead of class=""

### ISSUE THREAD

**Issue by mhaagens** [FormidableLabs/rapscallion#13]
<img width="673" alt="screen shot 2017-02-06 at 22 45 10" src="https://cloud.githubusercontent.com/assets/3270517/22667672/2550ade4-ecbe-11e6-888c-8b89cb60233e.png">

**Comment by divmain** [comment]
Thanks!  Totally missed that one.  Can you think of other special cases where `React` uses one identifier, but HTML uses something other than the dash-cased equivalent?

**Comment by kylecesmat** [comment]
@divmain Most JS `camelCased` attributes actually print to be lowercased, dash-casing is actually an exception. This is a decent list to reference: https://github.com/insin/babel-plugin-react-html-attrs/blob/master/lib/translations.js

**Comment by divmain** [comment]
Thanks to @alexlande for pointing me at [React's configs](https://github.com/facebook/react/tree/59ff7749eda0cd858d5ee568315bcba1be75a1ca/src/renderers/dom/shared) for prop conversion.

**Comment by divmain** [comment]
Fixed by #28.
