### ISSUE TITLE
No root checksum

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/rapscallion#14]
React internally provides a checksum here:

https://github.com/facebook/react/blob/e3131c1d55d6695c2f0966379535f88b813f912b/src/renderers/dom/stack/server/ReactMarkupChecksum.js

The client then checks this to see if it matches, and if it doesn't, it renders over it. Because we aren't providing a checksum at all, the client will always blow away what was server rendered with a fresh render, unnecessarily.

**Comment by aweary** [comment]
There are other attributes React includes as well that are required for full compatibility. Specifically `data-reactroot` and `data-reactid`.

**Comment by aweary** [comment]
Also, the checksum is calculated from the final markup, making it difficult (impossible?) to actually efficiently stream (as its being processed) the correct response since the first chunk would contain data that requires all the markup to be parsed already.

**Comment by divmain** [comment]
I've been considering this, and here are my thoughts:

- With Rapscallion, the checksum is not known until all rendering has completed.
- If streaming, the root element has already made it to the client by the time the checksum can possibly be generated.
- Fortunately, the checksum is not needed _on the client_ until the DOM has completed loading and React is bootstrapped.
- If the checksum were sent down in some format (global var wrapped in `<script`> tag, or attached to the DOM as a `data-` attribute somewhere), that value could be retrieved by the bootstrap code and attached to the corresponding DOM element.

It's a bit round-about, but it is the only way I can think of to make this happen.  And if we provide a nice utility to easily inject this information into the DOM, and possibly even mutate the DOM by injecting a script that takes care of everything for you, then it becomes a very much smaller downside.

**Comment by aweary** [comment]
@divmain we can at least implement this with `renderToString` since it is buffered. PR incoming.
