### ISSUE TITLE
Reliability

### ISSUE THREAD

**Issue by viktorbezdek** [FormidableLabs/rapscallion#21]
Howdy, is this library ready for prime time? Is it somehow battle tested?

I've project with about 500k unique visitors daily and 50-200 req/s all the time, so SSR performance and component level cache is crucial. Redis caching approach I came up with works but it's far from perfect. I know I won't have time to improve it soon enough, so I'm hoping for solution from open source scene.

**Comment by divmain** [comment]
Hi @viktorbezdek!

The first commit to was under a week ago, so this is definitely not battle-tested yet.  We're connected to a handful of folks with sizable deployments (your size and larger) with strong interest, so I expect stability to come rather quickly.

As people have taken a look, I've been able to address any issues that were identified pretty quickly.  If you're interested in getting this thing to a workable state, I'd welcome your involvement.  Unless you're particularly interested in development of the library itself, this would mean trying rapscallion in your own environment and reporting back on any issues you encountered.

If you don't have the bandwidth, that's completely fine!  We'll be announcing through various channels once we have confidence it's in a good state.

**Comment by divmain** [comment]
Oh!  And your comment re: Redis prompted a thought that I've documented here: #22.
