### ISSUE TITLE
Allow component cache to use alternative backend

### ISSUE THREAD

**Issue by divmain** [FormidableLabs/rapscallion#22]
Everything is in-memory for now.  However, caching is done with simple keys.  And once a cached component has been compressed, the values stored are simple strings.  This being the case, there's no reason why Redis couldn't be used as a backend.

Several benefits come to mind:

- TTLs for cache entries become simple to manage
- you don't risk out-of-memory errors in your Node process for folks caching anything and everything
- this scales across nodes
- you could also prime your cache using known keys

**Comment by ryan-roemer** [comment]
Or really, any distributed cache service (memcached, ElasticCache, etc.). Should be a pretty simple abstraction layer.

Put another way, I wouldn't tie it to Redis 😉

**Comment by divmain** [comment]
Agreed.  I've expanded my thoughts in the description for why Redis provides such great synergy.  But you're right - any caching service should be usable.  Ideally, the abstraction is agnostic to the storage, and you're only responsible for providing `get` and `set` functions that return a Promise.

**Comment by divmain** [comment]
Related to #5.
