### ISSUE TITLE
TypeError: (0 , _rapscallion.render) is not a function

### ISSUE THREAD

**Issue by mhaagens** [FormidableLabs/rapscallion#31]
Tried the new API and I'm getting ```TypeError: (0 , _rapscallion.render) is not a function``` from;
```
render(<App />).toPromise().then(application => {
   console.log(application)
})
```

**Comment by divmain** [comment]
Hey @mhaagens - I haven't published to NPM since updating the API and any changes since.  I was making a number of breaking changes and wanted to avoid three major revisions before I officially launched the thing :P  I'll publish this to a beta channel so you can give it a try.

**Comment by divmain** [comment]
Alright, you should be able to try out the updates by `npm install rapscallion@beta`.

**Comment by mhaagens** [comment]
Worked like a charm, thanks! :)
