### ISSUE TITLE
<br/> is double rendered

### ISSUE THREAD

**Issue by mini-eggs** [FormidableLabs/rapscallion#44]
Here's some photos showing the issue:
http://imgur.com/a/cwsjT

Last photo in the imgur list has javascript turned off.

Once I get the time I'll most likely submit a PR to help. :--)

**Comment by divmain** [comment]
That's super strange!  Thanks for reporting.

**Comment by mini-eggs** [comment]
No problem!

I guess it isn't really double rendered, just all jsx elements that are <something/> are turned into <something></something>

but browsers interpret <br></br> as two break points.

**Comment by aickin** [comment]
FYI, there are a bunch of other HTML elements that need to be self-closed when they have no content: https://github.com/facebook/react/blob/master/src/renderers/dom/stack/client/ReactDOMComponent.js#L354

**Comment by aweary** [comment]
@aickin mentioned in https://github.com/FormidableLabs/rapscallion/pull/45#issuecomment-283530710 👍 

btw we'd love any feedback or contributions you may have for the project in general @aickin!

**Comment by aickin** [comment]
> btw we'd love any feedback or contributions you may have for the project in general @aickin!

Four or five issues incoming right now! 😂

**Comment by mini-eggs** [comment]
Great link @aickin!

**Comment by divmain** [comment]
Closed by #54.
