### ISSUE TITLE
Template example code has an XSS security issue.

### ISSUE THREAD

**Issue by aickin** [FormidableLabs/rapscallion#46]
The [full example in the template section](https://github.com/FormidableLabs/rapscallion#example) has the following line:

```
window._initialState = ${() => JSON.stringify(store.getState())};
```

Unfortunately, `JSON.stringify` can cause XSS attacks when read out in the middle of a `<script>` tag. As [this article](https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0#.32wbmq52q) explains, a good solution is using the `serialize-javascript` module from npm.

**Comment by wmertens** [comment]
See #50
