### ISSUE TITLE
Yarn ./src directory

### ISSUE THREAD

**Issue by cescoferraro** [FormidableLabs/rapscallion#55]
I have installed this library with `yarn add rapscallion`

Then when I try to use it I get 

```
[0]     ERROR in ./~/rapscallion/index.js
[0]     Module not found: Error: Can't resolve './src' in '/srv/eat/node_modules/rapscallion'
[0]      @ ./~/rapscallion/index.js 5:19-35
[0]      @ ./src/middleware.tsx
[0]      @ multi ./src/middleware
[0] webpack: bundle is now VALID.
```

Because of thess [lines](https://github.com/FormidableLabs/rapscallion/blob/master/index.js#L1-L5)
My webpack config get mad about the fact that yarn does not bring the src directory and fails because cannot find it. How can I deal with these? removing the try/catch block solves  the issue `   module.exports = require("./lib");`

**Comment by divmain** [comment]
Hi @cescoferraro. 

This package isn't really intended to be used via Webpack. It's intended to be a server-side component only. What does your configuration look like? Are you using Webpack to transform your back-end code?

If the latter is true, one easy workaround would be to `require("rapscallion/lib")`. I'm open to changing what the module entry point looks like, too, if it's being consumed in ways I hadn't considered. 

Leery me know, and thanks for opening an issue.

**Comment by divmain** [comment]
Feel free to re-open if you need further help with this.
