### ISSUE TITLE
Differences in escaped/encoded text between React and Rapscallion

### ISSUE THREAD

**Issue by bmathews** [FormidableLabs/rapscallion#57]
This test fails due to differences in encoding charcode 39 between React and Rapscallion.

```
describe("text encoding", () => {
  const Component = () => <div>{"<script type='' src=\"\"></script>"}</div>;
  checkParity(Component, {});
});
```

We can either pull in `react-dom/lib/escapeTextContentForBrowser` as a dep and use it directly, or duplicate/copy the changes necessary for parity. 

https://github.com/facebook/react/blob/master/src/renderers/dom/shared/escapeTextContentForBrowser.js

**Comment by aweary** [comment]
We should probably just copy it directly and maintain our own version of it. Future releases of React may not expose internal modules under `react{-dom}/lib/*`

**Comment by divmain** [comment]
Agreed.  @bmathews, feel free to open another PR, and include the test above if possible.  And thanks!
