### ISSUE TITLE
TypeError: frameIterator.patch is not a function

### ISSUE THREAD

**Issue by clifton** [FormidableLabs/rapscallion#65]
When using setCacheStrategy on a memcached-backed store that returns promises I'm getting the following error:

```
node_modules/rapscallion/lib/sequence/sequence.js:49
      delegate();
      ^
TypeError: frameIterator.patch is not a function
```

config:

```
setCacheStrategy({
  get: (key) => cacheStore.get(key),
  set: (key, val) => cacheStore.set(key, val)
});
```

Adapter source is [here](https://gist.github.com/clifton/a087bd3b8ea7695dc96f559cb74780ad) but it is relatively simple (get/set returns promises and gets are batched).

**Comment by bmathews** [comment]
This is due to the `instanceof Promise` check we're doing, where `Promise` in our scope is `Bluebird` rather than a native Promise. We should probably just check if it is thenable.

**Comment by clifton** [comment]
ah, I'll use `Bluebird` for the time being. Thanks for the quick response!

**Comment by divmain** [comment]
Yeah, we'll change this to check for `then`ables.  Thanks for opening the issue @clifton!
