### ISSUE TITLE
Error thrown when using react-redux Provider

### ISSUE THREAD

**Issue by dortzur** [FormidableLabs/rapscallion#76]
Error thrown:
"Uncaught Error: React.Children.only expected to receive a single React element child."
From debugging I could see the provider didn't get any children. Not sure why.

minimal reproduction code:
```javascript
import React, { Component } from 'react';
import { render } from 'rapscallion/lib'
import { Provider } from 'react-redux';
class App extends Component {
    render() {
        return (
            <Provider>
                <div className="App" >
                hello joe
                </div>
            </Provider>
        );
    }
}
render(<App />).toPromise().then((html) => {
    console.log(html);
});
```
.babelrc
```json
 {
    "presets": [
      "env"
    ],
    "plugins": [
      "rapscallion/babel-plugin-server"
    ]
  }
```

**Comment by divmain** [comment]
Thanks for the simple repro!  I'll take a look at this.

**Comment by dortzur** [comment]
Thanks! We're switching to SSR and want to use Rapscallion in production (1 Billion monthly page views) if everything goes well.

**Comment by divmain** [comment]
@dortzur, can you pull down latest master to confirm the issue is resolved?
