### ISSUE TITLE
Not able to insert JSON string properly in HTML element attribute

### ISSUE THREAD

**Issue by MohitKansal** [FormidableLabs/rapscallion#79]
for ex:
var obj = {a:4};

react component
<input value={JSON.stringify(obj)} id="input_1" />

expected output
<input value='{"a":4}' id="input_1" />

but Rapscallion returns
<input value="{"a":4}" id="input_1" />

which leads to the erroneous input value.
when I try to get input value, it returns "{".

**Comment by divmain** [comment]
Hi @MohitKansal, I assume you're doing something like:
```javascript
return <input value={ JSON.stringify(obj) } id="input_1 />;
```
I can see how that would result in incorrect output.  Looks like we're not properly escaping the string attribute values.

**Comment by divmain** [comment]
This will be fixed in the next release.
