### ISSUE TITLE
Null components should be rendered

### ISSUE THREAD

**Issue by mohtar** [FormidableLabs/rapscallion#83]
Consider the empty component:

    class Empty extends React.Component {
      render() {
        return null;
      }
    }

Then rendering the component should result in placeholder in the form of HTML comment like so

    > ReactDOMServer.renderToString(<Empty />)
    ''

Instead Rapscallion just outputs an empty string. Client-side React will then complain about invalid checksum.

This should also work with `undefined` and `false`.

**Comment by ethersage** [comment]
Running into this as well.

**Comment by ethersage** [comment]
I think I can have a PR for this and some other other issues I found if this is something you're open to.
