### ISSUE TITLE
Async Cache Misses Render Empty or Out of Order

### ISSUE THREAD

**Issue by ethersage** [FormidableLabs/rapscallion#87]
I am setting my own async cache strategy. When the cache is empty and I `resolve(null)` in `get`, the rendered output of the component is being inserted later on in the output in the wrong place. It seems as if the component with a cacheKey is being rendered as the last child even if it is not the last child. I think renderChildren must be emitting all of the non-cached childen before the cached ones, probably because they're not waiting for `.then` to emit.

**Comment by maxgalbu** [comment]
I was having the same issue, the cached element was not rendered, but I did not see whether it was rendered at all. So it's "cache all components" or "cache none"?

**Comment by ethersage** [comment]
@maxgalbu I'm able to replicate that using this gist: https://gist.github.com/ethersage/1f5f696b43e62ab1ef8a9d9a9080cb96

**Comment by ethersage** [comment]
If I add a sibling cache key and tune the asynchronicity to 1 node, you get the following:

`<ul></ul><li>b</li><li>a</li>`

https://gist.github.com/ethersage/1a68e7dc1d69813c80c25ce78e38fe39

**Comment by ethersage** [comment]
Wrote some tests to verify the issue: https://github.com/FormidableLabs/rapscallion/pull/88

**Comment by Rymar** [comment]
I'm not sure if it's connected but i have similar cache issues, i made repo if you want to try it by yourself.

https://github.com/Rymar/rapscalion-cache
