### ISSUE TITLE
Promise not being Rejected on error?

### ISSUE THREAD

**Issue by tizmagik** [FormidableLabs/rapscallion#93]
Currently it looks like Rapscallion does not handle errors thrown in Components. So the `catch()` block here does not get hit:

```js
import React from 'react';
import { render } from 'rapscallion';

    render(
      <div>
        {() => { throw new Error('error!'); } }
      </div>
    )
      .toPromise()
      .then(html => {})
      .catch(err => {
        console.log(err);
      })
```

I'm not sure if this is expected behavior? Right now it seems the only way to catch the error is to add an `uncaughtException` handler.

**Comment by indeyets** [comment]
I see the same here. Each error pretty much kills the server ignoring catch-blocks we have in place.

**Comment by divmain** [comment]
This will be fixed in the next release.  Kudos to @fleg!
